### ISSUE TITLE
Can you tell me how to use it?

### ISSUE THREAD

**Issue by Viczyf** [Gazi13/Multiple-object-tracking-opencv-cpp#1]
Please write the detailed process how to run the code, thank you

**Comment by Gazi13** [comment]
To run this project the paths must be setting up properly.

Using same .sln file maybe can be a problem so, you can copy and paste the .cpp and .h files to a new visual studio project.

1. Change the paths according to your environment. 
2. Make sure opencv is installed properly. 
3. You can use Visual Studio, it makes much easier to run project. 
4. If you are using VS, I also uploaded the _.props_ file which ı am using. Maybe you need to set it according to your paths (Depending on where you installed the opencv).  But you don't have to use a .props files.

**Comment by Viczyf** [comment]
Thanks
